### ISSUE TITLE
Question: Param arguments

### ISSUE THREAD

**Issue by RenatoCesarF** [cangokceaslan/express-swagger-producer#1]
Does this package has path params? like : /user/:id?

Im trying to use it, but it wont work

```js
  /**
   * @route GET /notification/get/
   * @group notification
   * @param {string} userId.params.required
   * @returns {object} Notification List
   * @returns {Error}  default - Unexpected error
   */
  async get(req: Request, response: Response) {
      const userId = req.params.userId as string;
```

**Comment by cangokceaslan** [comment]
I think it will be like

`/users/{id}`

Default Swagger conventions is followed by this package, too

**Comment by RenatoCesarF** [comment]
Hi, thanks for the response, fixed it using this convenction that you said 

and using:

`   * @param {string} num.path.required`

would be good to add an example of path param in the documentation.

Thanks

**Comment by cangokceaslan** [comment]
Thank you,

I am glad that it is fixed.
